// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_7331x3l1MjJpec2GKxqljtsZEslk8I',
    appId: '1:795721527482:web:26e89135db71ec91e41283',
    messagingSenderId: '795721527482',
    projectId: 'things-reminder-df483',
    authDomain: 'things-reminder-df483.firebaseapp.com',
    storageBucket: 'things-reminder-df483.firebasestorage.app',
    measurementId: 'G-JBDKL81B20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkWLAnKV0mgRPORpvme1KCBMr97iLTtIc',
    appId: '1:795721527482:android:9f1938668721a315e41283',
    messagingSenderId: '795721527482',
    projectId: 'things-reminder-df483',
    storageBucket: 'things-reminder-df483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJQab0X_nNh3RKC8OngwfIf1YVdVQ_8Ns',
    appId: '1:795721527482:ios:700e4da787b9c624e41283',
    messagingSenderId: '795721527482',
    projectId: 'things-reminder-df483',
    storageBucket: 'things-reminder-df483.firebasestorage.app',
    iosBundleId: 'com.example.thingsReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJQab0X_nNh3RKC8OngwfIf1YVdVQ_8Ns',
    appId: '1:795721527482:ios:700e4da787b9c624e41283',
    messagingSenderId: '795721527482',
    projectId: 'things-reminder-df483',
    storageBucket: 'things-reminder-df483.firebasestorage.app',
    iosBundleId: 'com.example.thingsReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_7331x3l1MjJpec2GKxqljtsZEslk8I',
    appId: '1:795721527482:web:7700a9d3aceae5d7e41283',
    messagingSenderId: '795721527482',
    projectId: 'things-reminder-df483',
    authDomain: 'things-reminder-df483.firebaseapp.com',
    storageBucket: 'things-reminder-df483.firebasestorage.app',
    measurementId: 'G-EJN2X9YWHT',
  );
}
